[package]
name = "paradex"
version = "0.5.0"
edition = "2024"
license = "MIT"
description = "Paradex client library"
repository  = "https://github.com/snow-avocado/paradex-rs"

[dependencies]
cached = "0.55.1"
chrono = "0.4.40"
futures-util = "0.3.31"
jsonrpsee-core = "0.24.9"
jsonrpsee-types = "0.24.9"
log = "0.4.27"
reqwest =  {version="0.12.15", features=["json"]}
rust_decimal = {version="1.37.1", features=["serde"]}
serde = "1.0.219"
serde_json = "1.0.140"
starknet-core = "0.13.0"
starknet-crypto = "0.7.4"
starknet-signers = "0.11.0"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features=["full"]}
tokio-tungstenite = {version = "0.26.2", features=["native-tls"]}

[dev-dependencies]
simple_logger = "5.0.0"
criterion = "0.5.1"
mimalloc = "0.1.46"

[profile.bench]
debug = true

[[bench]]
name = "order_sign"
harness = false
